done API, tests and logs
AndreiNovikov1984/java-filmorate pull request #1
Opened 2022-09-11 20:14 UTC by AndreiNovikov1984

2022-09-13 16:16 UTC, andrew-larkin requested changes
Привет! Отличное приложение получилось, остается его немного отрефакторить и будет полностью готово.

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if ((film.getName() == null) || (film.getName().equals("")) || (film.getName().equals("null"))) {
давай перенесем все эти проверки в отдельный приватный метод. или даже лучше в статический метод в отдельном классе

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return postFilm(film);
лучше, конечно, не переиспользовать метод post - сделай здесь проверку на наличие данного фильма в коллекции и потом просто замени один другим. но провалидировать film перед этим тоже стоит (как в post)

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if ((user.getEmail() == null) || (user.getEmail().equals("")) || (user.getEmail().equals("null")) ||
см. комментарии в контроллере FilmController

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return postUser(user);
такая же ситуация как в FilmController

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/exeption/Exept.java
> +@ControllerAdvice
здорово, отдельный плюс за ControllerAdvice

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Getter
эти аннотации уже включены в аннотацию @Data, можно не использовать

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private static int identificator = 0;
думаю, в модель модификатор можно не добавлять, т.к. у нас уже есть id. Можно перенести identificator в контроллер, если хочешь его оставить

2022-09-13 16:16 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
см. комментарии к Film - тут все аналогично

2022-09-13 16:16 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    Film film;
все переменные, создаваемые не внутри методов, в тестах стоит добавлять с модификатором доступа private

2022-09-14 16:12 UTC, AndreiNovikov1984 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        return postFilm(film);
Мне тоже показалось не совсем правильно так делать, но получается практически одинаковые методы.....

2022-09-25 14:59 UTC, merged